### ISSUE TITLE
Ordered and unordered lists still not rendering right

### ISSUE THREAD

**Issue by ned14** [foonathan/standardese#100]
If you look at the class documentation for https://ned14.github.io/outcome/reference/outcome/#class-outcome-v2-xxx-outcome, nested ordered and unordered lists are still not rendering correctly.

**Comment by foonathan** [comment]
Yes, I have a fix currently going through CI.

Note that this is partly your fault: For CommonMark, children must start at the same indentation as the parent.
You have:

```
1. Foo
  - Child.
  - Child.
2. Bar
```

You need:

```
1. Foo
    - Child
    - Child
2. Bar
```

That and the fix on my part will make them render correctly.

**Comment by ned14** [comment]
Ok, I'll fix the indentation my end. BTW that verbatim support is working lovely, currently inserting links.

**Comment by foonathan** [comment]
Good to hear.
