### ISSUE TITLE
Function group names ought to be scoped local to the class owning them

### ISSUE THREAD

**Issue by ned14** [foonathan/standardese#103]
Also, an `\output_section` before a `\group` is ignored and does not appear in the output.

**Comment by foonathan** [comment]
They are supposed to now. Could you give an example?

**Comment by ned14** [comment]
In say https://ned14.github.io/outcome/reference/success_failure/#struct-outcome-v2-xxx-failure-type, you'll notice that I had to name the group's with unique names e.g. `failure_type_error`. If you name them all simple e.g. `error`, the group fails to be seen in the second class to use the same names as an earlier class.

**Comment by foonathan** [comment]
Are they injected groups?

**Comment by ned14** [comment]
`failure_type` is not. It is, however, a templated specialisation. Could that be it?

**Comment by foonathan** [comment]
That could be an issue, yes. I'll investigate it tomorrow.

**Comment by foonathan** [comment]
This was an oversight in the late night bugfix of the duplicate group issue, it is now fixed.

> Also, an \output_section before a \group is ignored and does not appear in the output.

This is (probably) the same as #104.
