### ISSUE TITLE
Handle attributes when parsing spelling

### ISSUE THREAD

**Issue by Manu343726** [foonathan/standardese#11]
When parsing classes with export/import attributes (For Windows DLLs) Standardese fails to parse the class spelling. [Here](https://gist.github.com/Manu343726/d623b89bd211f1e963efa9a68d9c437a)'s Standardese invocation on [siplasplas allocator library headers](https://github.com/GueimUCM/siplasplas/tree/master/include/siplasplas/allocator), which classes have export macros generated by cmake.

In the example output, the macros were generated for GCC on Linux, so the macro instantiations are `__attribute__((visibility("default")))` and `__attribute__((visibility("hidden")))`

**Comment by foonathan** [comment]
I know how to fix that but can't work on it the next few days. As a workaround you could use a macro and tell Standardese that it expands to nothing.
