### ISSUE TITLE
Tool reports that it cannot find wchar.h

### ISSUE THREAD

**Issue by tov** [foonathan/standardese#110]
The source code that causes the failure is:

```cpp
#include <iostream>
int f(int);
```

The problem seems to be that `<iostream>` includes files which eventually cannot find wchar.h. Here's the error message:

```
$ standardese test.h
parsing C++ files...
[preprocessor] [error] In file included from /Users/tov/project/int++/test.h: 1:
[preprocessor] [error] In file included from /usr/local/Cellar/llvm/5.0.1/include/c++/v1/iostream: 38:
[preprocessor] [error] In file included from /usr/local/Cellar/llvm/5.0.1/include/c++/v1/ios: 215:
[preprocessor] [error] In file included from /usr/local/Cellar/llvm/5.0.1/include/c++/v1/iosfwd: 90:
[preprocessor] [critical] /usr/local/Cellar/llvm/5.0.1/include/c++/v1/wchar.h:119: 'wchar.h' file not found
parsing documentation comments...
generating documentation...
writing files in format 'html'...
```

I'm able to compile programs that use `iostream` fine without any missing include errors.

This is with LLVM 5.0.1 on OS X 10.13.3.

**Comment by foonathan** [comment]
> [preprocessor] [critical] /usr/local/Cellar/llvm/5.0.1/include/c++/v1/wchar.h:119: 'wchar.h' file not found

Please show me what is written at that line, as well as the `LIBCLANG_SYSTEM_INCLUDE_DIR` CMake variable.

**Comment by tov** [comment]
Thanks for looking at this—I'm excited to try standardese.

The line in question is:

```cpp
#include_next <wchar.h>
```

And `LIBCLANG_SYSTEM_INCLUDE_DIR` is `/usr/local/Cellar/llvm/5.0.1/lib/clang/5.0.1/include`.

**Comment by foonathan** [comment]
Oh, I see the issue. Can you give me the path where the wchar.h is it tries to locate, so I can fix my CMake scripts?

Rebuilding standardese setting `LIBCLANG_SYSTEM_INCLUDE_DIR` to that directory (or manually add it with `-I`) will fix the problem.

**Comment by tov** [comment]
Sorry to be asking for what may be tech support at this point, but how do I find out the path to the wchar.h that it tries to locate? `locate wchar.h` gives me a lot, but nothing particularly promising. Could it be `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/wchar.h`?

**Comment by foonathan** [comment]
It could be that directory, run `clang++ -v /just/some/file.cpp` and it will print you the list of default include search directories and show them.

**Comment by tov** [comment]
That is indeed the right location. Adding

```
set(LIBCLANG_SYSTEM_INCLUDE_DIR
    /Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include)
```

to the root CMakeLists.txt and rebuilding does not seem to help. But passing the flag `-I    /Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include` made it work.

**Comment by foonathan** [comment]
Digging around that issue some more turned up this: https://github.com/Homebrew/homebrew-core/issues/8103 and this: https://stackoverflow.com/questions/19575956/building-c-not-working-in-osx-10-9

It seems to be that you built clang before/after doing something with XCode that messed up the default includes path of clang itself. So I don't think it is my fault, and you've found an easy workaround anyway.

**Comment by tov** [comment]
Interesting. Thank you.
