### ISSUE TITLE
What factor affects the C++ standards supported?

### ISSUE THREAD

**Issue by Hopobcn** [foonathan/standardese#114]
I'm curious on what factors affect the C++ support? 
Is the compiler used to parse all files the one responsible for the C++ standard support?

I am curious because firstly I compiled standardese locally using g++ 7.3.0 (llvm 6.0.0 also present) and I got up to C++17 support.
But then I tried to build standardese using Docker (using the same compilers) and I got up to C++14 support!
Here is my Dockerfile if you want to try:
```
FROM ubuntu:bionic

ARG git_branch=develop
ARG llvm_includedir=/usr/lib/llvm-6.0/include
ARG llvm_clang_includedir=/usr/lib/llvm-6.0/lib/clang/6.0.0/include/

# dependences
RUN apt update && apt install -y                                                                                       \
    ca-certificates git cmake build-essential llvm-dev clang libclang-dev python python3                               \
    libboost-filesystem-dev libboost-system-dev libboost-thread-dev libboost-date-time-dev                             \
    libboost-chrono-dev libboost-atomic-dev libboost-program-options-dev

RUN git clone https://github.com/foonathan/standardese.git -b ${git_branch} /standardese

RUN llvm_includedir=$(llvm-config --includedir)
RUN llvm_clang_includedir=$(llvm-config --prefix)/lib/clang/$(llvm-config --version)/include/

RUN mkdir -p /standardese/build && cd /standardese/build;                                                              \
    cmake -DSTANDARDESE_BUILD_TEST=OFF                                                                                 \
          -DLIBCLANG_INCLUDE_DIR=$llvm_includedir                                                                      \
          -DLIBCLANG_SYSTEM_INCLUDE_DIR=$llvm_clang_includedir .. &&                                                   \
    make -j4

RUN cp -r /standardese/build/tool/standardese /usr/local/bin/

RUN rm -rf /standardese

ENTRYPOINT [ "standardese" ]
```
Shouldn't gcc 7.3.0 / llvm 6.0.0 result in a standardese build compatible with C++17?

------------------------------------------------------------------------------------------------------------------------
local standardese output:
```
  --compilation.standard arg (=c++14)                       the C++ standard to use for parsing, 
                                                            valid values are c++98/03/11/14/1z/17
```
dockerfile standardese output:
```
  --compilation.standard arg (=c++14)                       the C++ standard to use for parsing, 
                                                            valid values are c++98/03/11/14
```

**Comment by foonathan** [comment]
Nothing depends on the support it is hard coded (see https://github.com/foonathan/standardese/blob/develop/tool/main.cpp#L351)

Are you sure your docker build used the develop branch? On master there is indeed no C++17.

(I should *really* merge develop at some point...)

**Comment by Hopobcn** [comment]
I'm confused because I changed nothing to my docker script and now it works fine :-D (maybe docker was caching something...)
Thanks!

> Are you sure your docker build used the develop branch?

Yes, I was cloning standardese repo specifiying the branch with `-b ${git_branch}`.

**Comment by ricejasonf** [comment]
It's better to use a specific git SHA revision in the Dockerfile so it doesn't get cached.

Shameless plug: https://youtu.be/lmIc0MgWBEI :smile:
