### ISSUE TITLE
Can I pass arbitrary flags to the compiler?

### ISSUE THREAD

**Issue by njlr** [foonathan/standardese#115]
I need to enable some niche Clang flags (`-f*-ts`) in order to build my code. Is there a way to pass arbitrary flags to Clang in standardese?

**Comment by foonathan** [comment]
Sadly, no, not at the moment.

I'm busy with my Meeting C++ talk, will implement it in two weeks.

**Comment by foonathan** [comment]
Okay, now it's done: `--compilation.feature=modules` or `-f modules`.
