### ISSUE TITLE
Dropping Boost?

### ISSUE THREAD

**Issue by parnmatt** [foonathan/standardese#116]
Currently you take care of all dependencies except `libclang` for obvious reasons, and boost.

Rather than using Boost.ProgramOptions, how about using a header only library like [Phil Nash's Clara](https://github.com/catchorg/Clara)

I personally use the following in one of my projects

```cmake
# Clara
set(clara_include_dir ${CMAKE_CURRENT_BINARY_DIR}/clara/include)
file(DOWNLOAD https://github.com/catchorg/Clara/releases/download/v1.1.4/clara.hpp ${clara_include_dir}/clara/clara.hpp
	EXPECTED_HASH MD5=dd92f20a27ab40b3c8f7e387020e23e4)
add_library(clara INTERFACE)
target_include_directories(clara INTERFACE ${clara_include_dir})
```

*note to self, I should make an alias to `clara::clara` in that project to be consistent with everything else*

It's actually quite nice to work with.

And for Boost.Filesystem, would it not be possible to check if you are using GCC 8, or Clang 7, and compiling in C++17 onwards, and thus use `std::filesystem`, I believe their interfaces are basically the same as `std::filesystem` was based on Boost.Filesystem.

With something like:

```cxx
#if USE_STD_FILESYSTEM
#include <filesystem>
namespace fs = std::filesystem;
#else 
#include <boost/filesytem.hpp>
// other filesystem includes
namespace fs = boost::filesystem;
#endif
```
where needed.

---

That way, those of us using C++17 do not need to link against boost at all, and you've dropped a dependency that you were required to manually install for some of your users; without impacting your other users.

**Comment by foonathan** [comment]
I was planning on doing that as well, but Boost.ProgramOptions supports getting options from config files which is nice. I haven't found a library that does that as well. If I have a replacement for that I will drop Boost.

If you're on Linux, I do have a convenience docker image for building it, see the readme.

**Comment by parnmatt** [comment]
I see where that would be useful. I know that if you can pass a `TokenStream` which can be constructed from a `std::vector<std::string>::const_iterator` pair.
Which is fairly simple to get from a `std::ifstream`; it would have to be argument format, or at least in a format you can parse into that format ... but then you'd have to deal with an `ini` parser dependency too to keep full compatibility.
Shame `TokenStream` explicitly uses `std::vector<std::string>::const_iterator` rather than any pair of iterators with a `std::iterator_traits<It>::value_type` of `std::string`, thus skipping needing to store in a vector... I'll probably make a pull request for that at some point.

**Comment by foonathan** [comment]
Ideally I would somehow make it work with cxxopts, as that is already an dependency of cppast

**Comment by parnmatt** [comment]
:+1:
