### ISSUE TITLE
Error with comments is macro parameters

### ISSUE THREAD

**Issue by ilyapopov** [foonathan/standardese#119]
Current latest version 44fbe78b2e73f890535bf1c927401f5834ca42a4

1.hpp:
```
#define macro(/* comment */ x) ((x)*(x))
```

Command line:

    standardese 1.hpp

Output:

```
parsing C++ files...
[preprocessor] [error] xxx/1.hpp:1: invalid token in macro parameter list
parsing documentation comments...
generating documentation...
writing files in format 'html'...
```

**Comment by foonathan** [comment]
If they're parse error, please submit them to cppast, yes.

**Comment by foonathan** [comment]
Please check the feature/comments-macro branch and see if that works.

**Comment by ilyapopov** [comment]
I confirm that "invalid token" error is gone.

**Comment by foonathan** [comment]
I've merged the branch, so I'm closing this one.
