### ISSUE TITLE
Assertion failed (cursor is reference) at cpp_namespace.cpp:52

### ISSUE THREAD

**Issue by Manu343726** [foonathan/standardese#12]
Full log [here](https://gist.github.com/Manu343726/bc6d9093e8e97fcee88d5fdadfa0cd99).

**Comment by foonathan** [comment]
This is AFAIK triggered by a using declaration. Please provide all using declarations of that file or a reduced source code.

**Comment by Manu343726** [comment]
File is [`siplasplas/reflection/dynamic/function.hpp`](https://github.com/GueimUCM/siplasplas/blob/dynamic-reflection-runtime/include/siplasplas/reflection/dynamic/function.hpp).

**Comment by foonathan** [comment]
Type aliases are different code, I have a guess but cannot work on it until Friday.

**Comment by Manu343726** [comment]
NP
