### ISSUE TITLE
Potential mishandling of BOOST_PP_STRINGIZE

### ISSUE THREAD

**Issue by brook-milligan** [foonathan/standardese#121]
Standardese fails with 'file not found' errors on files that include certain Boost headers; see below for an example.  It seems that this results from a (mis-?)handling by standardese of BOOST_PP_STRINGIZE to generate file names that are not actually file names (see the /**/ below).

In this example, the contents of 'end.hpp' are simply

   #include <boost/range/end.hpp>

Note that including <boost/range/end.hpp> in normal code compiles just fine, of course.

standardese --verbose -I/path/to/include end.hpp
parsing C++ files...
[preprocessor] [error] In file included from /path/to/end.hpp: 1:
[preprocessor] [error] In file included from /path/to/include/boost/range/end.hpp: 24:
[preprocessor] [error] In file included from /path/to/include/boost/range/detail/implementation_help.hpp: 15:
[preprocessor] [error] In file included from /path/to/include/boost/range/detail/common.hpp: 24:
[preprocessor] [error] In file included from /path/to/include/boost/mpl/or.hpp: 43:
[preprocessor] [critical] /path/to/include/boost/mpl/aux_/include_preprocessed.hpp:37: 'boost/mpl/aux_/preprocessed/gcc/or.hpp /**/' file not found
[preprocessor] [error] /path/to/include/boost/preprocessor/stringize.hpp:28: note: expanded from macro 'BOOST_PP_STRINGIZE'
[preprocessor] [error] /path/to/include/boost/preprocessor/stringize.hpp:31: note: expanded from macro 'BOOST_PP_STRINGIZE_I'
[preprocessor] [error] <scratch space>:138: note: expanded from here

[end.hpp.gz](https://github.com/foonathan/standardese/files/2801292/end.hpp.gz)

**Comment by foonathan** [comment]
Could you build the `cppast` executable as well (CPPAST_BUILD_TOOL=ON) and check whether `cppast --verbose -I/path/to/include --remove_comments_in_macro` fixes it?

**Comment by foonathan** [comment]
Or check the feature/comments-macro branch and see if that works.

**Comment by brook-milligan** [comment]
> On Feb 1, 2019, at 6:32 PM, Jonathan Müller <notifications@github.com> wrote:
> 
> Could you build the cppast executable as well (CPPAST_BUILD_TOOL=ON) and check whether cppast --verbose -I/path/to/include --remove_comments_in_macro fixes it?

That does indeed fix it.  I also ran it across some subset of boost and there do not seem to be errors.

Note, however, that I had to use the syntax "-I /path/to/include" (note the space after -I). Do you expect the syntax given above to work?

Note also that I downloaded the cppast application separately from your github page.  If there is something else integrated into standardese I have not tried it.

Cheers,
Brook

**Comment by brook-milligan** [comment]
> On Feb 2, 2019, at 5:12 PM, Jonathan Müller <notifications@github.com> wrote:
> 
> To clarify: the branch works?

I hadn't tried the branch, just cppast from your other repository.

I have now tried the standardese branch, which does seem to work on the file (end.hpp) that failed before.

By the way, -IXXX (no space) seems to work with standardese.  Perhaps there is different handling between the two programs?

Cheers,
Brook

**Comment by foonathan** [comment]
I've now merged the branch, so I'm closing this one.

> By the way, -IXXX (no space) seems to work with standardese. Perhaps there is different handling between the two programs?

Yes, they use different command line parsing libraries.
