### ISSUE TITLE
How would standardese handle the following case?

### ISSUE THREAD

**Issue by ruipacheco** [foonathan/standardese#122]
I'm currently coming across the limits of Doxygen and was wondering if standardese has an answer for this case: https://stackoverflow.com/q/54483956/70600

**Comment by foonathan** [comment]
I don't have native support for that either. Best you can do is describe it in plain text i.e. "it will invoke `callback`, passing it the error code that...", or document a sample callback function somewhere else.

**Comment by ruipacheco** [comment]
Thanks!
