### ISSUE TITLE
Cannot build on Mac OS with Clang

### ISSUE THREAD

**Issue by tcbrindle** [foonathan/standardese#13]
Attempting to build with Clang/libc++ on Mac OS gives the error:

```
/Users/tristan/Coding/standardese/include/standardese/string.hpp:130:72: error: no member named '~string' in 'std::__1::basic_string<char>'
                static_cast<std::string*>(get_storage())->std::string::~string();
```
I can't say I understand this as there clearly *is* a destructor defined for `std::string`, but there we are. The same code compiles without warning using GCC 6.1/libstdc++.

If you need any more info please let me know.

**Comment by foonathan** [comment]
Yeah, I need to look up the proper syntax for that.

**Comment by mkurdej** [comment]
Since `string` is a typedef to `basic_string<char>`, the destructor name is still `~basic_string`.

IMHO, this should work:
```
                static_cast<std::string*>(get_storage())->std::string::~basic_string();
```

or even better:
```
                static_cast<std::string*>(get_storage())->~basic_string();
```
