### ISSUE TITLE
Support for variable template

### ISSUE THREAD

**Issue by foonathan** [foonathan/standardese#2]
Due to libclang 3.7 limitations there is no support for variable or alias templates.
Variable templates become normal variables and alias templates are simply ignored.

Before a libclang version gets available try to work around that somehow.

**Comment by foonathan** [comment]
Under libclang 3.8 or higher alias templates are now supported.

**Comment by purpleKarrot** [comment]
You might consider using libtooling instead of libclang. This is what @chandlerc recommended to @agserm and @bgeller for copperspice/doxypress.

**Comment by foonathan** [comment]
Yeah, I know I should. But I got it working except for this issue and #39, so I see what I can do.

**Comment by agserm** [comment]
As @purpleKarrot noted, libclang will most likely never support the level of parsing you need for a documentation engine. We discovered this in developing doxypress. The libclang interface is really oriented toward a code completion use case, and basically supports "whatever XCode needed to understand." We tried to make libclang work for our case but eventually realized it would be futile and we would be fighting the API every step of the way.

**Comment by foonathan** [comment]
I was able to get all the information I wanted, because I've coupled libclang with my own parser that scans the tokens of a cursor.

The problem with variable templates is that - last time I've checked - they are reported as regular variables, so I was not able to get the template information. This seems to be a libclang bug though.

**Comment by foonathan** [comment]
This is now tracked here: https://github.com/foonathan/cppast/issues/11
