### ISSUE TITLE
Segfault in test

### ISSUE THREAD

**Issue by tcbrindle** [foonathan/standardese#20]
The `cpp_using_declaration` test segfaults on MacOS:

```~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
standardese_test is a Catch v1.5.5 host application.
Run with -? for options

-------------------------------------------------------------------------------
cpp_using_declaration
-------------------------------------------------------------------------------
../test/cpp_namespace.cpp:296
...............................................................................

../test/cpp_namespace.cpp:296: FAILED:
  {Unknown expression after the reported line}
due to a fatal error condition:

  SIGSEGV - Segmentation violation signal

===============================================================================
test cases:  11 |  10 passed | 1 failed
assertions: 359 | 358 passed | 1 failed
```

**Comment by tcbrindle** [comment]
Stepping through with the debugger, it appears that the issue is in cpp_entity_registry.hpp line 105:

```cpp
return scope.empty() ? name : std::string(scope.c_str()) + "::" + name.c_str();
```

My guess is that `scope.c_str()` is returning `nullptr`, which causes a segfault when passed to `std::string`'s constructor. [Passing `nullptr` to `std::string::string()` [is undefined behaviour](http://en.cppreference.com/w/cpp/string/basic_string/basic_string) -- see notes for overload 4. I think libstdc++ lets you get away with it, but libc++ does not.]

**Comment by tcbrindle** [comment]
Investigating further, the problem seems to be with the placement new in `standardese::string::string(const string& other)` (string.hpp:61):

``` cpp
string(const string &other)
: length_(other.length_), type_(std_string)
{
    ::new(get_storage()) std::string(other.c_str());
}
```

Valgrind reports "Invalid read of size 1" on this line.

**Comment by foonathan** [comment]
Hm, couldn't reproduce with clang and libstdc++, I'm investigating further.

**Comment by foonathan** [comment]
I ran into an issue there as well with MSVC, fixed it there.
Hopefully that also fixes your issue.

But I think my fix is just a workaround and there are deeper issues with `standardese::string`.

**Comment by tcbrindle** [comment]
Yep, fixed now on OS X 👍

**Comment by foonathan** [comment]
But as I feared, only a workaround, now crashes under Travis.

**Comment by foonathan** [comment]
Okay, nevermind Travis didn't had the workarounds.

But I still think there is an issue.
