### ISSUE TITLE
Add clang and OS X to travis CI

### ISSUE THREAD

**Issue by mkurdej** [foonathan/standardese#24]
It would be nice to have continuous integration with all major compilers (clang is missing) and major platforms (OS X is missing).

**Comment by foonathan** [comment]
I look into that.

I cannot use clang on Travis under Linux because clang doesn't like the standard library version, so only clang under OS X.

**Comment by mkurdej** [comment]
What's the problem with clang?

Look here for example: https://github.com/edouarda/brigand/blob/master/.travis.yml, it uses clang on Linux without any problems.

If it's the problem with the standard library, can you add `-stdlib=libc++` or `-stdlib=libstdc++` argument?

**Comment by foonathan** [comment]
I got this error: https://travis-ci.org/foonathan/standardese/jobs/137038QD486

I remember having issues myself.

**Comment by mkurdej** [comment]
Nice job!
