### ISSUE TITLE
Assertion failure when parsing `__cplusplus` or `_MSC_VER` macros

### ISSUE THREAD

**Issue by mkurdej** [foonathan/standardese#27]
It happens at least on MSVC 2015u2, Win10.
Assertion at `tokenizer.cpp:101` fails:

```
    assert(buf.is_open());
```

The reason is however already before, since the line `tokenizer.cpp:86`:

```
    clang_getSpellingLocation(begin, &file, nullptr, nullptr, &begin_offset);
```

doesn't check if file has been modified or is still null (or uninitialized).

**Comment by foonathan** [comment]
Could you provide a source code example which triggers this?

**Comment by mkurdej** [comment]
Yep, I was minimizing the file, here it is:

```
#ifndef ISSUE27_H
#define ISSUE27_H

#ifdef __cplusplus
extern "C" {
#endif

#ifdef _MSC_VER
typedef __time64_t my_time_t;
#else

#ifdef __cplusplus
} // extern "C"
#endif

#endif // ISSUE27_H
```

Normally, assertion triggers on extern "C" declaration.
If you remove extern, then you'll get assertion on `_MSC_VER`.

**Comment by mkurdej** [comment]
From what I see, extern declarations have cursor type `CXCursor_UnexposedDecl` which is not handled.

**Comment by foonathan** [comment]
I just fix support for those predefined macros, could you check it out?

**Comment by mkurdej** [comment]
Just my 2 cents:

- You haven't formatted the sources with clang-format
- No new tests for these macros.

I dont' know what the policy of this project is, but it would be nice if everyone (the owner being no exception) added tests before fixing the issue.

BTW, I still have an assertion failure (but different than before), investigating.

**Comment by foonathan** [comment]
I am currently on vacation, just quickly wanted to fix your issue.

**Comment by mkurdej** [comment]
Assertion failure in `std::string::operator[]`: caused by `cpp_preprocessor.cpp:parse_macro::43`:
```
    while (std::isspace(source[i]))
```

In your fix, you `return "";` when cannot get the file from source range (in `read_source`).
Now, we should handle the case in `parse_macro` where `source` gets assigned `""`, so `source.size() == 0`.

**Comment by mkurdej** [comment]
An (ugly) quick fix:
Change cpp_preprocessor.cpp:42 from:
```
        auto i = name.length();
```
to
```
        auto i = source.length();
```

**Comment by foonathan** [comment]
I've now fixed that as well, although some other issue I've noticed.
