### ISSUE TITLE
`assert` failure when combining comparison with template parameters

### ISSUE THREAD

**Issue by johnmcfarlane** [foonathan/standardese#31]
When the following source file is passed to the `standardese` command

```c++
#include <type_traits>

template<int Exponent, typename std::enable_if<!(Exponent<=0) && (Exponent<8), int>::type Dummy = 0>
constexpr int pow2()
{
    return pow2<int, Exponent-1>()*2;
}
```

the program crashes with the following output
> [info] Generating documentation for "fixed_point.h"...
standardese: /home/john/github/foonathan/standardese/src/detail/parse_utils.cpp:57: void standardese::detail::unmunch(std::__cxx11::string&): Assertion `balance == 0 || balance == -1' failed.

and `balance` set to 2.

It appears that the comparison operator `<` is being incorrectly parsed as the open brace to a template parameter list. The excerpt is part of [this header file](https://github.com/johnmcfarlane/fixed_point/blob/master/include/sg14/fixed_point.h).

**Comment by foonathan** [comment]
Shit, yes it is.

**Comment by foonathan** [comment]
This fix is going to take longer, it requires restructuring part of my parsing.

**Comment by johnmcfarlane** [comment]
No problem. I'm already using Doxygen and was just taking a casual 'test drive'. 

Excuse my ignorance of libclang but could you ask for the template parameters as a list - rather than a flat string?

**Comment by foonathan** [comment]
It was actually much more straightforward: I just need to also count the parentheses and if there are open ones, don't count the angle brackets because than we are inside an expression.

It is now fixed on the develop branch.

**Comment by johnmcfarlane** [comment]
This is still happening but on a different line:
```c++
str="typename std::enable_if<\nExponent<0,\nint>::type"
balance=1
parens = 0
```
The project I linked to above is full of equally gnarly templates.

**Comment by foonathan** [comment]
I see that I can parse the entire project then before coming back :D

**Comment by johnmcfarlane** [comment]
That would be nice. :smile: If you can get _fixed_point.h_ working, you'll be half-way there.

**Comment by foonathan** [comment]
Now it is fixed.

This issue can only occur for specializations again because otherwise I simply removed the code that looks at the template parameters and did an alternative.

Note that standardese cannot parse your auxiliary headers, to be precise: the functions generated by macros due to a bug with libclang. But the public headers work and only they need to be documented, right?

**Comment by johnmcfarlane** [comment]
Thanks. That sounds like a problem that should mostly affect [integer.h](https://github.com/johnmcfarlane/fixed_point/blob/master/include/sg14/auxiliary/integer.h). For comparison here's [fixed_point.h](https://github.com/johnmcfarlane/fixed_point/blob/9bbbd2e6dd0bc04d8ce388220539b3f2c50fec5a/include/sg14/fixed_point.h) in both [Standardese](https://gist.github.com/johnmcfarlane/e9d9aac94c849b393aa584190d21412c) and [Doxygen](http://johnmcfarlane.github.io/fixed_point/fixed__point_8h.html). Not bad for a source file marked up for Doxygen. Clearly, some work would be required get the best results.

**Comment by foonathan** [comment]
There seems to be a regression with the formatting of namespaces (closing bracket in the same line as the last entity).

And I also need to tweak some things in the output.

But my overall goal with standardese is that you can get the same format as the C++ standard documentation with the right markup. This could be useful for you proposal writers.
