### ISSUE TITLE
segmentation fault when using exceptions

### ISSUE THREAD

**Issue by stakewinner00** [foonathan/standardese#33]
When using try-catch block inside some scope (like a member function in a class) it works, but if not it gives a segmentation fault.

For example 

```cpp
template<typename T>
void foo(T& myarg) try {
} catch(int whatever) {
}
```
The backtrace: 
[bt.txt](https://github.com/foonathan/standardese/files/374741/bt.txt)

**Comment by foonathan** [comment]
I'm getting an assertion failure for that input. Have you compiled with assertions disabled?

Anyways, I've fixed the assertion, that problem hopefully caused your segfault as well.

**Comment by stakewinner00** [comment]
I don't have explicitly disabled assertions, I used the default values.
Anyway, it seems to be fixed now.
