### ISSUE TITLE
tokenizer::read_source() assertion failed

### ISSUE THREAD

**Issue by Manu343726** [foonathan/standardese#34]
Core dump:

```
standardese: /home/manu343726/Documentos/siplasplas/build/THIRDPARTY/standardese/src/standardese/src/detail/tokenizer.cpp:205: static std::string standardese::detail::tokenizer::read_source(standardese::translation_unit &, standardese::cpp_cursor): Assertion `clang_File_isEqual(file, tu.get_cxfile())' failed.
```

The input are the header files [here](https://github.com/Manu343726/siplasplas/blob/master/include/siplasplas/utility). (standardese command generated from [here](https://github.com/Manu343726/siplasplas/blob/master/3rdParty/standardese/CMakeLists.txt)), assertion failed when parsing `exception.hpp`.

**Comment by foonathan** [comment]
This should be fixed now.
