### ISSUE TITLE
Error when parsing anonymous enumeration

### ISSUE THREAD

**Issue by xaxousis** [foonathan/standardese#38]
When parsing an anonymous enumeration in a structure such as
```c++
struct Foo {
    enum {bar = 0};
};
```
I get the following error:
```
[error] when parsing '' (file:line): expected '' got '{'
```
The error disappears if the enumeration is given a name.

**Comment by foonathan** [comment]
Thanks for noticing, stupid oversight. Is fixed on the develop branch.

**Comment by xaxousis** [comment]
Super quick reaction time ! I checked the fix, it triggers an assertion error:
```
.../standardese/src/cpp_enum.cpp:63: static standardese::cpp_ptr<standardese::cpp_enum_value> standardese::cpp_enum_value::parse(standardese::translation_unit&, standardese::cpp_cursor, const standardese::cpp_entity&): Assertion `!"enum type is neither signed nor unsigned"' failed.
Abandon
```

**Comment by foonathan** [comment]
Yeah, I was close to pushing the patch and this was a very easy fix :D

The assertion failure is weird, don't have that for me.
Is this on the same code you've posted? What is the output of `standardese --version`?

**Comment by xaxousis** [comment]
No, it's on a more complicated one I'm trying to see how to reproduce now.

```
standardese version 0.2
Copyright (C) 2016 Jonathan Müller <jonathanmueller.dev@gmail.com>

Using libclang version: clang version 3.8.0 (tags/RELEASE_380/final)
Using cmark version: 0.25.2
```

**Comment by xaxousis** [comment]
Okay, still an enum problem. It happens in a trait structure.
```c++
template<class T>
struct has_foo {
    template<class U, decltype(U::foo)* = nullptr>
    static constexpr bool check(U*)  {return true;}
    static constexpr bool check(...) {return false;}
    enum {value = check(static_cast<T*>(nullptr))};
};
```

**Comment by foonathan** [comment]
Okay, that's an issue because the type depends on the template parameter.
Resolving this takes more than one hour :D

**Comment by foonathan** [comment]
Apparently it took 3 hours, please confirm.

**Comment by xaxousis** [comment]
Just checked, it seems everything's ok now.

Thank you :D
