### ISSUE TITLE
A friend function inside a class raises a warning and is not documented

### ISSUE THREAD

**Issue by xaxousis** [foonathan/standardese#39]
A friend declaration raises the following warning:

```
[warning] when parsing '' (file:line): Unknown cursor kind 'UnexposedDecl'
```

If the definition is inline, the function's documentation is not extracted.

Example:

``` cpp
/** A test class */
struct Test {
    /** A sample friend function */
    friend void foo();
};
```

**Comment by foonathan** [comment]
Yes, that is a libclang limitation.

**Comment by foonathan** [comment]
I've managed to fix it on develop.

It will silently ignore all friend declarations (as they are implementation details) *unless* they are friend function definitions as they create a new function.

I.e.:

```cpp
/// Foo.
struct foo
{
  // ignored
  friend struct bar;

  // ignored
  friend void foo();

  /// Documented.
  friend void swap(foo& a, foo& b)
  {
     // ...
  }
};
```
