### ISSUE TITLE
Preprocessing #error

### ISSUE THREAD

**Issue by xaxousis** [foonathan/standardese#42]
Hello,

The following fails to compile with the latest release (v0.2-2) and the latest develop (#5e03c95)

``` cpp
#if __cplusplus <= 201103
#error "Should not appear for C++11 & C++14"
#endif
```

The error is : 

```
[critical] when parsing '<unknown>' (test.cpp:2): encountered #error directive or #pragma wave stop() (Boost.Wave)
```

**Comment by foonathan** [comment]
Hm, it seems that the __cplusplus macro isn't defined properly.

**Comment by xaxousis** [comment]
I forgot to mention I compiled with the clang 3.9 release.

**Comment by foonathan** [comment]
Just a heads-up: While this is in theory a simple problem, I'm forced to abandon Boost.Wave and reimplement macro expansion and conditional compilation so the fix could  take a while.

**Comment by foonathan** [comment]
Alright, this is fixed now.
