### ISSUE TITLE
Compiling on Fedora linux 

### ISSUE THREAD

**Issue by gbellizio** [foonathan/standardese#43]
Running cmake on Fedora 25 using standard system clang packages gives an error:

```
...
CMake Error at external/external.cmake:56 (message):
  3.7.1 unable to find clang's system header files, please set
  LIBCLANG_SYSTEM_INCLUDE_DIR yourself
Call Stack (most recent call first):
  CMakeLists.txt:16 (include)
```
I fixed the error by adding the path `/usr/lib64` to `CLANG_LIBRARY_PATHS` variable in `external/external.cmake`

**Comment by foonathan** [comment]
Thanks I'll add it as well.
