### ISSUE TITLE
cannot document function parameters when functions are in a group

### ISSUE THREAD

**Issue by rollbear** [foonathan/standardese#46]
Example code:

```Cpp
/// \group func
/// does something
/// \param a first
/// \param b second
void func(int a, int b);

/// \group func
void func(int a);
```

The documented output becomes:

  # Header file `t.h`<a id="t.h"></a>

  ``` cpp
  void func(int a, int b);

  void func(int a);
  ```

  ## Function `func`<a id="t.h"></a>

  ``` cpp
  (1)    void func(int a, int b);

  (2)    void func(int a);
  ```

  does something

Output from `standardese` run with `--verbose=1` is:

```txt
[debug] Using libclang version: clang version 3.9.1-svn281634-1~exp1 (branches/release_39)
[debug] Using cmark version: 0.25.2
[info] Generating documentation for "/tmp/t.h"...
[debug] parsing entity 'func(int, int)' (/tmp/t.h:5) of type 'FunctionDecl'
[debug] parsing entity 'func(int)' (/tmp/t.h:8) of type 'FunctionDecl'
[info] Generating indices...
[info] Writing files for output format md...
[debug] writing documentation file 't'
[debug] writing documentation file 'standardese_entities'
```

For templates, the template parameters can be `\exclude`d per part in the group, but not otherwise documented.

Documenting the parameters of each variant in a group is useful. See e.g. [any_of](http://en.cppreference.com/w/cpp/algorithm/all_any_none_of) on `cppreference.com`

**Comment by foonathan** [comment]
And it will document all parameters (or all inline documentation) of all members.

**Comment by rollbear** [comment]
Confirmed.
