### ISSUE TITLE
Cannot \exclude template parameter if preceded by parameter pack

### ISSUE THREAD

**Issue by rollbear** [foonathan/standardese#47]
Example code:

```Cpp
#include <utility>

/// makes a T from n parameters
/// \param T target type
/// \param 2
/// \exclude
template <typename T, typename ... U, typename = std::enable_if_t<std::is_constructible<T, U...>{}>>
T make_t_m(U&& ...u);

/// makes a T from a parameter
/// \param T target type
/// \param 2
/// \exclude
template <typename T, typename U, typename = std::enable_if_t<std::is_constructible<T, U>{}>>
T make_t(U&& u);
```

The generated documentation does not `\exclude` the SFINAE typename for `make_t_m()`, but does so for `make_t()`.

No error-indicating output when run with `--verbose=1`.

**Comment by foonathan** [comment]
Does it work if you give the parameter a name?

**Comment by rollbear** [comment]
Yes, it does. Thanks! Although it does clutter the code in an unpleasant way.

**Comment by foonathan** [comment]
Sure, I'll fix it anyway. :)

I just supsected - read "hoped" - that it was an issue with the automatic parameter naming code.

**Comment by foonathan** [comment]
Fixed on develop.

**Comment by rollbear** [comment]
Confirmed
