### ISSUE TITLE
Link/Emphasis within param documentation fires assert

### ISSUE THREAD

**Issue by TartanLlama** [foonathan/standardese#49]
Putting a link within a function parameter documentation comment triggers an assertion.

Standardese version from git, commit 0fe0e6630cda75c361b9f3a008077af5f70e7d0d.
Platform: Arch Linux x64

Minimal source code:

```
/// \param foo [std::vector]()
void bar(int foo);
```
Output of `standardese --verbose`:

> [debug] Using libclang version: clang version 3.8.1 (tags/RELEASE_381/final)
> [debug] Using cmark version: 0.26.1
> [info] Generating documentation for "temp.hpp"...
> standardese: /home/simon/aur/standardese-git/src/standardese/src/comment.cpp:556: void {anonymous}::container_stack::pop(): Assertion `!stack_.empty()' failed.
> [1]    20106 abort (core dumped)  standardese --verbose temp.hpp
>

**Comment by foonathan** [comment]
Just a heads up: I won't be able to fix it very quickly as it requires restructuring how the markdown is parsed.

**Comment by foonathan** [comment]
Okay, managed a somewhat hacky fix.
