### ISSUE TITLE
Example/code tag

### ISSUE THREAD

**Issue by nyorain** [foonathan/standardese#50]
Some basic usage examples are often really useful for documenting code. How about introducing a code or example tag in standardese? They could be different to doxygen but at the moment there is no way to conveniently provide code examples for functions or classes (please correct me if I'm wrong).

Otherwise using standardese to document code is way cleaner and easier than doxygen, thank you 👍

**Comment by foonathan** [comment]
It's on my (never-ending) TODO list for this project. :)

**Comment by nyorain** [comment]
oh ok, then i guess i'll try to implement it. Do you have any concept for a possible tag? I would probably prefer using the \example tag with an inline description and code snippet similiar to the examples on cppreference.

**Comment by foonathan** [comment]
You can already embed code snippets and regular text in standardese doc comments, so the following works:

```
/// This is documentation.
///
/// See example:
/// ```cpp
/// int a = 42;
/// int c = a + 3;
/// std::cout << c << '\n';
/// ```
```

The only thing missing for a proper example would be the relevant section in the output, so a `\example` command like `\effects` etc.

**Comment by foonathan** [comment]
On second thoughts, I don't think `\example` is that necessary - unless you think otherwise?

**Comment by nyorain** [comment]
yes, you are right, pretty much what I thought as well after seeing your example. Just using code snippets is probably enough, no need for an extra tag. Feel free to close this issue.
At least one point less on your TODO list ;)
