### ISSUE TITLE
Documentation for Compiling with LLVM from brew on Mac

### ISSUE THREAD

**Issue by nilsdeppe** [foonathan/standardese#51]
I think adding a section for compiling with LLVM that is installed via brew on Macs could be helpful. Here is the CMake command I had to use for LLVM 3.9.0

```shell
cmake -DSTANDARDESE_BUILD_TEST=OFF -DLIBCLANG_INCLUDE_DIR=/usr/local/opt/llvm/include -DLIBCLANG_LIBRARY=/usr/local/opt/llvm/lib/libclang.dylib -DLIBCLANG_SYSTEM_INCLUDE_DIR=/usr/local/opt/llvm/lib/clang/3.9.0/include ..
```

The version of LLVM only shows up in the LIBCLANG_SYSTEM_INCLUDE_DIR and from my tests can even be replaced by  a wildcard, so

```shell
cmake -DSTANDARDESE_BUILD_TEST=OFF -DLIBCLANG_INCLUDE_DIR=/usr/local/opt/llvm/include -DLIBCLANG_LIBRARY=/usr/local/opt/llvm/lib/libclang.dylib -DLIBCLANG_SYSTEM_INCLUDE_DIR=/usr/local/opt/llvm/lib/clang/*/include ..
```
seems to also work correctly.

**Comment by foonathan** [comment]
Could you provide a PR? I have no experience with MacOS.

**Comment by nilsdeppe** [comment]
Sure! I'll work on it in the coming days.

**Comment by foonathan** [comment]
Any update on this? :D
