### ISSUE TITLE
Clicking on Namespace Name Doesn't Show Namespace

### ISSUE THREAD

**Issue by nilsdeppe** [foonathan/standardese#52]
When clicking on a namespace one is redirected to the first file (alphabetically, I think) that contains that namespace rather than a page that contains a list of all the entities in a particular namespace.

e.g. with brigand, clicking on the "lazy" namespace redirects to the documentation for `types/inherit_linearly.hpp` rather than a list of all the entities in the namespace.

**Comment by foonathan** [comment]
The link for namespaces and modules will now point to the index where that namespace or module is documented. All entities in that namespace/module can be found below.

**Comment by nilsdeppe** [comment]
After running brigand through it now I get

```
Assertion failed: (!is_name()), function file_name, file /Users/nils/SpECTRE/standardese/include/standardese/comment.hpp, line 134.
Abort trap: 6
```

with no documentation being generated. Is this just me? The culprit commit is 9267de537fcf026d3765e859f54a709dd30b4e93

**Comment by foonathan** [comment]
No, my fault, tests on Win are failing to. Will fix tomorrow.

**Comment by nilsdeppe** [comment]
Cool, thank you!

**Comment by foonathan** [comment]
All fixed now.

**Comment by nilsdeppe** [comment]
Works for me. Thank you!
