### ISSUE TITLE
Failure to compile under Alpine Linux with current releases of spdlog and standardese

### ISSUE THREAD

**Issue by qbradq** [foonathan/standardese#55]
I am really excited about this tool but have been unable to get it to compile within by build container. I get this error when compiling standardese from current HEAD and latest tag, both when letting the cmake scripts download spdlog and when manually specifying the include directory of the latest spdlog tag.

```
In file included from /tmp/standardese/src/detail/synopsis_utils.cpp:5:
In file included from /tmp/standardese/include/standardese/detail/synopsis_utils.hpp:10:
In file included from /tmp/standardese/include/standardese/parser.hpp:13:
In file included from /usr/local/include/spdlog/logger.h:15:
In file included from /usr/local/include/spdlog/sinks/base_sink.h:13:
In file included from /usr/local/include/spdlog/sinks/sink.h:9:
In file included from /usr/local/include/spdlog/details/log_msg.h:9:
/usr/local/include/spdlog/details/os.h:354:12: error: no matching conversion for functional-style cast from 'int' to 'std::string' (aka 'basic_string<char>')
    return std::string(strerror_r(err_num, buf, buf_size));
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/bin/../lib/gcc/x86_64-alpine-linux-musl/6.2.1/../../../../include/c++/6.2.1/bits/basic_string.h:389:7: note: candidate constructor not viable: no known conversion from 'int' to 'const std::allocator<char>' for 1st argument
      basic_string(const _Alloc& __a) _GLIBCXX_NOEXCEPT
      ^
```

Compiler is clang 3.8.1

Here is the Dockerfile that reproduces the issue: https://raw.githubusercontent.com/qbradq/sosaria-online/1337274c4e8cea387dc276d8ade0db7a20e8abcf/docker/build/Dockerfile

**Comment by foonathan** [comment]
This seems like an issue in spdlog, have you tried manually cloning it's latest version and use that?

**Comment by foonathan** [comment]
Hey @gabime, can you take a lock?

**Comment by stopher2** [comment]
i have the same problem with ALPINE builds using spdlog

EXCERPT:
./include/spdlog/details/os.h:  In function 'std::__cxx1::string spdlog:;details:;os::errno_str(int)':
./include/spdlog/details/os.h:389:58: error: no matching function for call to 'std::__cxx11::basic_string<char>::basic_string(int)'
return std::string(strerror_r(err_num, buf, buf_size));

et al     
string.h
basic_string.h
os.h

./include spdlog/details/os.h:389:34: error: invalid conversion from 'int' to 'const char*' [-fpermissive]
  return std::string(strerror_r(err_num, buf, buf_size));
..

**Comment by gabime** [comment]
@stopher2 Which version of spdlog?

**Comment by foonathan** [comment]
The current master branch uses the (very old) https://github.com/gabime/spdlog/tree/4fcde3b8508364deb4321baba6fef02cc3b59a44 (I should update it).

**Comment by stopher2** [comment]
am thinking that the upstream gabime/spdlog conversation WRT Alpine is the right place for this ?

**Comment by gabime** [comment]
@foonathan Try upgrading.  i think it was fixed already
