### ISSUE TITLE
cldoc?

### ISSUE THREAD

**Issue by Alexander-Shukaev** [foonathan/standardese#57]
Hello, may I kindly ask whether you are aware of [jessevdk/cldoc](http://github.com/jessevdk/cldoc)?  And if yes, then what's the point of yet another effort compared to the linked one?

**Comment by foonathan** [comment]
I wasn't aware of that project.

But I think standardese has support for advanced documentation features, cldoc lacks. (And cldoc has a nicer output, standardese lacks).
