### ISSUE TITLE
Allow inheriting documentation

### ISSUE THREAD

**Issue by ned14** [foonathan/standardese#59]
I have a template type which composites itself from many class fragments inside namespace detail depending on its input types.

I'd like the documentation for the member functions inside the class fragments inside namespace detail to be inherited and displayed in the most derived class.

I do not want to document the class fragments inside namespace detail. I just want the public member functions inherited to appear in the documentation.

**Comment by foonathan** [comment]
Yes, that's on my internal todo list as well.

**Comment by foonathan** [comment]
This is done in 9eda19b010e9fd0c9f828a138cae2cfcb55beb48
