### ISSUE TITLE
std::ifstream is used but <fstream> is not included

### ISSUE THREAD

**Issue by odinthenerd** [foonathan/standardese#69]
I get an error here https://github.com/foonathan/standardese/blob/develop/tool/main.cpp#L71
```
main.cpp:71:30: error: variable ‘std::ifstream config’ has initializer but incomplete type
         std::ifstream config(path.string());
                              ^
```
which I think is because `std::ifstream` is used but `<fstream>` is not included, including it solves the problem.

**Comment by foonathan** [comment]
Yes, need to setup CI again.
