### ISSUE TITLE
Two headers with same name but different extension are parsed into same documentation output file

### ISSUE THREAD

**Issue by ned14** [foonathan/standardese#73]
If feeding:
- `result.hpp`
- `result.h`

... to standardese, it generates the same file `doc_result.html`, thus overwriting one of the files.

It should spot when the name is the same, and call is `doc_result.hpp.html` and `doc_result.h.html` or something.

**Comment by foonathan** [comment]
I've added a new `\output_name` command. It can be used to specify the output name of the file:

result.hpp
```
/// \file
/// \output_name result.hpp
```

**Comment by ned14** [comment]
It would be better if this was automatic and not require additional markup. It avoids surprise.

Also, \output_name appears to not be working. I have it at https://github.com/ned14/outcome/blob/develop/include/outcome/result.h#L28 but no effect.

**Comment by ned14** [comment]
Just wanted to say that after this morning's pass through, the docs are looking serviceable. A few bits of incorrect output, no doubt the peer review will identify all of it. Only really this issue to fix to complete the full set of docs being made available, the rest of it I can likely workaround in some form. Thanks Jonathan!

**Comment by foonathan** [comment]
You need:
```
/// \file
/// \output_name ...
```
Otherwise it's not a file comment.

I'll think about automating it.
