### ISSUE TITLE
Cannot suppress items from output

### ISSUE THREAD

**Issue by ned14** [foonathan/standardese#74]
Some of my macros are solely internal expansion macros used to implement other macros. They are never called by user code. Yet they still appear in the output.

Solutions:

1. If the entity is undocumented, don't show it.
2. If the entity has a documentation of `//! \exclude` or `//! \suppress`, remove it.

**Comment by foonathan** [comment]
This should already be the case (`\exclude` are hidden away), can you give an example?

**Comment by foonathan** [comment]
I need an example that doesn't work.

**Comment by ned14** [comment]
My apologies, this is fixed.
