### ISSUE TITLE
In the standardese_entities file, namespaces inline with types

### ISSUE THREAD

**Issue by ned14** [foonathan/standardese#75]
I am finding the current system of sorting nested namespaces inline with types for a namespace unhelpful. If one is searching for a type, one wants to see all of those together, not broken out over multiple pages with spam namespaces in the way, distracting you. If namespaces could be pushed all to the bottom of the page, that would be great.

**Comment by foonathan** [comment]
I've added an `output.entity_index_order` option. If you set it to `namespace_external` it will create a separate list for each namespace which is imo a better solution to your problem.
