### ISSUE TITLE
Restore Markdown output support

### ISSUE THREAD

**Issue by ned14** [foonathan/standardese#80]
And consider support for any one or more of the other formats Hugo supports:

MMark, Asciidoc, restructuredtext

Some of these support annotating code blocks with clickable links to jump to the detailed documentation.

**Comment by foonathan** [comment]
I've added now commonmark and commonmark_html output. The latter uses HTML for codeblocks and anchors.

**Comment by ned14** [comment]
Cool, the commonmark_html works particularly well. But why do the links to documentation later in the same file repeat the file name? It causes a 404.

**Comment by foonathan** [comment]
You have to specify `--output.link_extension` to override the extension of the file.

**Comment by ned14** [comment]
Markdown docs are online, looks like I'll need to do a bit of path munging anyway as I want the policies in a separate path https://ned14.github.io/outcome/reference/policies/. But thanks for the fix!

**Comment by foonathan** [comment]
I've noticed a lot of issues there, though. Some of which are my fault, working on them.

**Comment by foonathan** [comment]
> But why do the links to documentation later in the same file repeat the file name? It causes a 404.

Misunderstood the problem. This isn't an issue on my end, but how relative links are treated. I've added a new option `--output.link_prefix` that can be used to convert the relative links into absolute ones (not yet pushed).

**Comment by foonathan** [comment]
Okay, merged.
