### ISSUE TITLE
Namespace generation error

### ISSUE THREAD

**Issue by ned14** [foonathan/standardese#82]
https://ned14.github.io/outcome/standardese/doc_success_failure.html#standardese-outcome_v2_xxx::failure_type%3CEC,E%3E

```
template <class EC = std::error_code, class E = void>
struct failure_type
{
    using error_type = EC;
    using exception_type = E;

    outcome_v2_xxx::failure_type::error_type _error;
    outcome_v2_xxx::failure_type::exception_type _exception;
```

Why is it printing the full namespace of error_type and exception_ptr?

**Comment by foonathan** [comment]
This is fixed in cppast, will become available here once I merge.
