### ISSUE TITLE
Entire of outcome.hpp appears not to be parsed at all

### ISSUE THREAD

**Issue by ned14** [foonathan/standardese#83]
See https://ned14.github.io/outcome/standardese/doc_outcome.html, nothing is documented.

**Comment by ned14** [comment]
Well, actually kinda need this issue fixed too, the lack of any docs from outcome.hpp is definitely unhelpful.

**Comment by foonathan** [comment]
Yes, it's next on my agenda.

**Comment by foonathan** [comment]
Fixed in cppast, includes at the bottom of the file confused my comment matcher (turns out includes are not reported ordered relative to other entities so you just can't skip over them all...).

**Comment by ned14** [comment]
Can you let me know when this updated cppast reaches standardese please? Thanks

**Comment by foonathan** [comment]
Now

**Comment by ned14** [comment]
https://ned14.github.io/outcome/reference/outcome#standardese-outcome_v2_xxx is looking much better now, thank you. Though the main outcome<> class description is still having its numbered lists and nested items mis-parsed.

Last remaining big item I think is the `result.h` issue. Oh, be aware that Boost peer review hates to ever see `detail::` in reference docs. I'm not personally as zealous on that, but some get real upset about it. I'm personally happy to leave them in until the review and see who complains and how loudly.

Thanks Jonathan!

**Comment by foonathan** [comment]
>  Though the main outcome<> class description is still having its numbered lists and nested items mis-parsed.

I look into it again.

> Last remaining big item I think is the result.h issue.

It works, you just have to turn into a file comment as I said.

> Oh, be aware that Boost peer review hates to ever see detail:: in reference docs

Just generate the documentation with `--input.exclude_namespace=detail`.

**Comment by ned14** [comment]
Got the C API docs generated.

> Just generate the documentation with --input.exclude_namespace=detail.

Made no difference. I'm already blacklisting the detail namespace.

**Comment by foonathan** [comment]
You are referring to the base class, right? Fixed that as well, push it later today.

I also implemented the inlining of excluded bases, however, it can't handle the conditional in your case.

**Comment by ned14** [comment]
> You are referring to the base class, right? Fixed that as well, push it later today.

No. If you search https://ned14.github.io/outcome/reference/outcome/ for `detail::`, you'll see what I mean.

**Comment by foonathan** [comment]
I see. I think most of those are due to libclang limitations I can try to workaround.

But note that you should probably run with `--output.show_complex_noexcept=false` to make the noexcepts a little bit better.
