### ISSUE TITLE
first attempted use on windows

### ISSUE THREAD

**Issue by wovo** [foonathan/standardese#85]
I am totally new to both standardese (and clang), but I'd like to give it a try. The main page says "There is a pre-built binary for Windows 64 Bit, found in the release pages, built with Appveyor and MSVC 14. You need to install libclang but should work out the box otherwise." but the link to libclang is to a page that doesn't have any item called libclang. As a best guess, I installed the clang for windows 64 binary.

Now running "standardese hwlib-all.cpp" (my main header file) gives

C:\ti-software\hwcpp\library>"C:\Program Files\standardese\standardese" hwcpp-all.hpp
[1m[info] Generating documentation for "hwcpp-all.hpp"...
[00m[31m[1m[error] [preprocessor] hwcpp-all.hpp
[00m[31m[1m[error] [preprocessor] :40:10: fatal error: 'cstddef' file not found
#include <cstddef>
         ^~~~~~~~~

[00m[31m[1m[error] [preprocessor] 1
[00m[31m[1m[error] [preprocessor]  error generated.

[00m[1m[41m[critical] Command 'C:/Program Files/LLVM/bin/clang++.exe -E -CC -Wno-pragma-once-outside-header "-x" "c++" "-I" "C:\Program Files\LLVM\lib\clang\3.9.0\include" "-std=c++14" "-fms-extensions" "-fms-compatibility" "-fms-compatibility-version=19" hwcpp-all.hpp' failed with exit code '1'

Those "[00m" look weird, but I can live with that. But for the include error, what am I to do about that?

**Comment by foonathan** [comment]
Those weird question marks are part of the ASCII control sequences used for color in the logger, there is a command line option to disable color on Windows as they're not supported there.

Yes, installing clang was correct.

The pre-built binaries have hardcoded the standard library include dir, but it is probably different on your machine, you have to pass `-I /path/to/standard/library/headers` to standardese.

**Comment by wovo** [comment]
I have not used clang, so I am not sure what that path should be. The first file missing is cstddef. That file doesn't seem to be anywhere in the LLVM I installed. Should I install something else? Or somehow use the GCC libraries?

**Comment by foonathan** [comment]
It is under `<clang-install-dir>/lib/clang/<version>/include`.

**Comment by wovo** [comment]
That's what I tried first, but there are no C++ headers there. I re-installed LLVM, but there were no boxes to cross to install more things. (There was a message during installation that MSVC integration failed.)

**Comment by wovo** [comment]
I get the same error when I just use clang++ to compile the same sources. I suppose clang++ should know where its headers are, so it seems to be an LLVM installation problem?

**Comment by wovo** [comment]
It seems to work now stealing the MINGW header files:

STANDARDESE += -I "$(MINGW)\lib\gcc\x86_64-w64-mingw32\7.2.0\include\c++"
STANDARDESE += -I "$(MINGW)\lib\gcc\x86_64-w64-mingw32\7.2.0\include\c++\x86_64-w64-mingw32"
STANDARDESE += -I "$(MINGW)\x86_64-w64-mingw32\include"

next problem: concepts...
