### ISSUE TITLE
Sorely need a \verbatim command to pass through unmodified text

### ISSUE THREAD

**Issue by ned14** [foonathan/standardese#95]
I need to pass through Hugo markup into what Standardese outputs. An implementation of doxygen's \verbatim would do nicely: https://www.stack.nl/~dimitri/doxygen/manual/commands.html#cmdverbatim

**Comment by foonathan** [comment]
This is somewhat tricky to implement as standardese does does some reordering of contents sometimes. What kind of markup are we talking about?

**Comment by ned14** [comment]
```
    then `throw std::system_error(error()|make_error_code(error()))` [\verbatim {{<api "policies/result_error_code_throw_as_system_error" "policy::error_code_throw_as_system_error<S>">}} \endverbatim]
```

**Comment by foonathan** [comment]
What is the high level feature you are trying to achieve?

**Comment by ned14** [comment]
Ability to link to other sections of the Hugo website, so the tutorial, other reference docs, and so on. That's the `{{< api X Y >}}` markup. One could use hardcoded URLs, but it's much nicer to reference what you want, and let Hugo do the linking. This also gets added to the semantic search etc

**Comment by foonathan** [comment]
In the template which I haven't implemented again, you were able to place some markers in the additional documentation and let standardese link to those. So you could write,  for example:

```
{{ some_special_standardese_syntax_i_forgot foo }}
This is some tutorial.
```

And then in documentation comments:

```
See also [foo](standardese://foo/)
```

Would that be sufficient or do you need Hugo to do the linking?

**Comment by ned14** [comment]
Trouble is I don't want to insert links, I want to insert magic markup which tooling which consumes standardese output groks. Your suggestion solution would be brittle - I want to link to a magic identifier which hugo converts into links, letting me reorganise docs without breaking anything.

**Comment by foonathan** [comment]
Yes, that it was this does as well: it provides a magic identifier you can link to.

**Comment by foonathan** [comment]
I've added `\verbatim` and `\end`. It can be used like code spans in CommonMark, so `\verbatim VERBATIM text \end`. It strips leading and trailing whitespace and cannot span multiple lines.
