### ISSUE TITLE
More than just `Requires` clause

### ISSUE THREAD

**Issue by akrzemi1** [foonathan/standardese#96]
Would you consider adding more clauses to library function specifications. This paper
http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2016/p0411r0.html proposes to separate *Requires:* clause into:

- *Requires:* -- static requirements: if not satisfied, the program does not compile (static asserts, enable_if-s, concepts)
- *Preconditions:* -- dynamic requirements on values; if not satisfied, the program has UB.

I think it would be a useful improvement to library specifications.

**Comment by foonathan** [comment]
I have both of those already: https://github.com/foonathan/standardese/blob/develop/include/standardese/markup/doc_section.hpp#L19-L41

**Comment by akrzemi1** [comment]
Splendid. Thanks!
