### ISSUE TITLE
Inherited documentation is not adding documentation blocks?

### ISSUE THREAD

**Issue by ned14** [foonathan/standardese#99]
It looks to me that inherited member functions are appearing in the class synopsis at the front, but they then link to documentation pages generated from blacklisted files and namespaces. They do not inherit the documentation into the child class.

Blacklisted namespaces and files need to have no evidence in the output, so inherited member functions from blacklisted parents need to appear as if defined in the child class.

**Comment by foonathan** [comment]
I thought I'd fix the link issue...

Could you give me an example?

**Comment by ned14** [comment]
Actually I am wrong. Sorry, call it confusion through exhaustion.
